FROM node:18-alpine AS BUILD

WORKDIR /app

# Copy package files
COPY package*.json ./
RUN npm install

# Copy source code (files in root)
COPY . .

# Build the app (output in /dist)
RUN npm run build

# Production Stage
FROM nginx:alpine

# Copy build artifacts
COPY --FROM=BUILD /app/dist /usr/share/nginx/html

# Copy custom Nginx config
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
